export const ADD_TODO = 'ADD_TODO'
export const CHANGE_STATUS = 'CHANGE_STATUS'
export const DELETE_TODO = 'DELETE_TODO'
export const EDIT_TODO = 'EDIT_TODO'

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const SET_PRIORITY_FILTER = 'SET_PRIORITY_FILTER'
export const SET_KEYWORD = 'SET_KEYWORD'

export const VISIBILITY_FILTERS = {
    SHOW_ALL: 'SHOW_ALL',
    SHOW_COMPLETED: 'SHOW_COMPLETED',
    SHOW_ACTIVE: 'SHOW_ACTIVE'
}

export const PRIORITY_FILTERS = {
    SHOW_ALL: 'SHOW_ALL',
    SHOW_LOW: 'SHOW_LOW',
    SHOW_HIGH: 'SHOW_HIGH'
}